# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Ecom-poc CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # create-envfile:
 
  #   runs-on: ubuntu-latest
 
  #   steps:
  #   - name: Make envfile
  #     uses: SpicyPizza/create-envfile@v1.3
  #     with:
  #       envkey_DEBUG: false
  #       envkey_SOME_API_KEY: "123456abcdef"
  #       envkey_SECRET_KEY: "bla"
  #       some_other_variable: foobar
  #       file_name: .env
  #       fail_on_empty: false
  #   - run: ls -a  
  CI:
    # needs: create-envfile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create .env file
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_DATABASE_URL: "postgres://uneeb.saleem:PZ8hFfit2pOz@ep-nameless-glitter-897635-pooler.ap-southeast-1.aws.neon.tech/neondb?pgbouncer=true&connect_timeout=10"
        envkey_PORT: "8080"
        envkey_JWT_TOKEN_PRIVATE_KEY: "80d81dfea47bcb7fd88997426db168a52c4d3e2feefd52a9b29552362c5aee1da2c186b4d0c2b66964f11869cdfe1ee3d36b5e82ea5eeff6bae04708dbcf59e3"  
        envkey_JWT_EXPIRATION: "2 days"
    - run: ls -a
    - run: sudo cp .env /dist
    - run: ls -a
    - run: npm ci
    - run: npm run build 
    - run: npm run test
  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ecom-poc"
          heroku_email: "uneeb.saleem@10pearls.com"