# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Ecom-poc CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI:
    # needs: create-envfile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create .env file
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
        envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
        envkey_JWT_TOKEN_PRIVATE_KEY: ${{ secrets.JWT_TOKEN_PRIVATE_KEY }}
    - run: npm ci
    - run: npm run build
    - run: npm run test
    - run: ls -a
    - run: sudo mv /github/workspace/.env /github/workspace/dist
    - run: cd dist
    - run: ls -a
    - run: cd dist
    - run: ls -a
  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ecom-poc"
          heroku_email: "uneeb.saleem@10pearls.com"  
    - run: ls -a    
